[package]
name = "starkzuri"
version = "0.1.0"
edition = "2024_07"

[dependencies]
# Match this to your Scarb version (2.14.0)
starknet = "2.14.0"

[dev-dependencies]
# Use the Modern Library. Tag v0.33.0 is stable.
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.52.0" }

[[target.starknet-contract]]
sierra = true
casm=true

[scripts]
test = "snforge test"